<?php
return [
    'Curut Terbang',
    'Knalpot Racing',
    'Kucing Gembul',
    'Anjing Ompong',
    'Kodok Ngorok',
    'Biawak Gabut',
    'Bebek Joget',
    'Burung Dangdut',
    'Kupu-Kupu Malam',
    'Cacing Kalung',
    'Hantu Ngakak',
    'Nenek Lampir Senyum',
    'Tuyul Goyang',
    'Mbah Surip Tertawa',
    'Kuntilanak Genit',
    'Pocong Dance',
    'Sundel Bolong Selfie',
    'Genderuwo Selfie',
    'Leak Jomblo',
    'Buto Ijo Imut',
    'Buto Putih Joget',
    'Kuyang Ketawa',
    'Tuyul Selfie',
    'Hantu Gagal Fokus',
    'Kuntilanak Fashionista',
    'Jelangkung Ngakak',
    'Wewe Gombel Ketawa',
    'Tuyul Ganteng',
    'Pocong Happy',
    'Sundel Bolong Happy',
    'Kuntilanak Ketawa',
    'Buto Ijo Genit',
    'Leak Lucu',
    'Buto Putih Lucu',
    'Kuyang Happy',
    'Tuyul Joget',
    'Hantu Selfie',
    'Kuntilanak Gagal Fokus',
    'Jelangkung Joget',
    'Wewe Gombel Joget',
    'Tuyul Lucu',
    'Pocong Joget',
    'Sundel Bolong Genit',
    'Kuntilanak Happy',
    'Buto Ijo Joget',
    'Leak Joget',
    'Buto Putih Joget',
    'Kuyang Joget',
    'Tuyul Ketawa',
    'Hantu Joget',
    'Kuntilanak Lucu',
    'Jelangkung Lucu',
    'Wewe Gombel Lucu',
    'Tuyul Ngakak',
    'Pocong Lucu',
    'Sundel Bolong Joget',
    'Kuntilanak Joget',
    'Buto Ijo Happy',
    'Leak Ketawa',
    'Buto Putih Happy',
    'Kuyang Ketawa',
    'Tuyul Genit',
    'Hantu Happy',
    'Kuntilanak Genit',
    'Jelangkung Happy',
    'Wewe Gombel Happy',
    'Tuyul Joget',
    'Pocong Ketawa',
    'Sundel Bolong Ketawa',
    'Kuntilanak Ketawa',
    'Buto Ijo Lucu',
    'Leak Lucu',
    'Buto Putih Lucu',
    'Kuyang Lucu',
    'Tuyul Selfie',
    'Hantu Lucu',
    'Kuntilanak Selfie',
    'Jelangkung Selfie',
    'Wewe Gombel Selfie',
    'Tuyul Ketawa',
    'Pocong Selfie',
    'Sundel Bolong Selfie',
    'Kuntilanak Selfie',
    'Buto Ijo Selfie',
    'Leak Selfie',
    'Buto Putih Selfie',
    'Kuyang Selfie',
    'Tuyul Lucu',
    'Hantu Lucu',
    'Kuntilanak Lucu',
    'Jelangkung Lucu',
    'Wewe Gombel Lucu',
    'Tuyul Genit',
    'Pocong Lucu',
    'Sundel Bolong Lucu',
    'Kuntilanak Genit',
    'Buto Ijo Genit',
    'Leak Genit',
    'Buto Putih Genit',
    'Kuyang Genit',
    'Tuyul Joget',
    'Hantu Genit',
    'Kuntilanak Joget',
    'Jelangkung Joget',
    'Wewe Gombel Joget',
    'Tuyul Ketawa',
    'Pocong Genit',
    'Sundel Bolong Genit',
    'Kuntilanak Ketawa',
    'Buto Ijo Ketawa',
    'Leak Ketawa',
    'Buto Putih Ketawa',
    'Kuyang Ketawa',
    'Tuyul Happy',
    'Hantu Joget',
    'Kuntilanak Joget',
    'Jelangkung Joget',
    'Wewe Gombel Joget',
    'Tuyul Selfie',
    'Pocong Joget',
    'Sundel Bolong Joget',
    'Kuntilanak Happy',
    'Buto Ijo Happy',
    'Leak Happy',
    'Buto Putih Happy',
    'Kuyang Happy',
    'Tuyul Lucu',
    'Hantu Happy',
    'Kuntilanak Happy',
    'Jelangkung Happy',
    'Wewe Gombel Happy',
    'Tuyul Ketawa',
    'Pocong Happy',
    'Sundel Bolong Happy',
    'Kuntilanak Ketawa',
    'Buto Ijo Ketawa',
    'Leak Ketawa',
    'Buto Putih Ketawa',
    'Kuyang Ketawa',
    'Tuyul Genit',
    'Hantu Ketawa',
    'Kuntilanak Ketawa',
    'Jelangkung Ketawa',
    'Wewe Gombel Ketawa',
    'Tuyul Joget',
    'Pocong Ketawa',
    'Sundel Bolong Ketawa',
    'Kuntilanak Joget',
    'Buto Ijo Joget',
    'Leak Joget',
    'Buto Putih Joget',
    'Kuyang Joget',
    'Tuyul Happy',
    'Hantu Joget',
    'Kuntilanak Joget',
    'Jelangkung Joget',
    'Wewe Gombel Joget',
    'Tuyul Selfie',
    'Pocong Joget',
    'Sundel Bolong Joget',
    'Kuntilanak Happy',
    'Buto Ijo Happy',
    'Leak Happy',
    'Buto Putih Happy',
    'Kuyang Happy',
    'Tuyul Lucu',
    'Hantu Happy',
    'Kuntilanak Happy',
    'Jelangkung Happy',
    'Wewe Gombel Happy',
    'Tuyul Ketawa',
    'Pocong Happy',
    'Sundel Bolong Happy',
    'Kuntilanak Ketawa',
    'Buto Ijo Ketawa',
    'Leak Ketawa',
    'Buto Putih Ketawa',
    'Kuyang Ketawa',
    'Tuyul Genit',
    'Hantu Ketawa',
    'Kuntilanak Ketawa',
    'Jelangkung Ketawa',
    'Wewe Gombel Ketawa',
    'Tuyul Joget',
    'Pocong Ketawa',
    'Sundel Bolong Ketawa',
    'Kuntilanak Joget',
    'Buto Ijo Joget',
    'Leak Joget',
    'Buto Putih Joget',
    'Kuyang Joget',
    'Tuyul Happy',
    'Hantu Joget',
    'Kuntilanak Joget',
    'Jelangkung Joget',
    'Wewe Gombel Joget',
    'Tuyul Selfie',
    'Pocong Joget',
    'Sundel Bolong Joget',
    'Kuntilanak Happy',
    'Buto Ijo Happy',
    'Leak Happy',
    'Buto Putih Happy',
    'Kuyang Happy',
    'Tuyul Lucu',
    'Hantu Happy',
    'Kuntilanak Happy',
    'Jelangkung Happy',
    'Wewe Gombel Happy',
    'Tuyul Ketawa',
    'Pocong Happy',
    'Sundel Bolong Happy',
    'Kuntilanak Ketawa',
    'Buto Ijo Ketawa',
    'Leak Ketawa',
    'Buto Putih Ketawa',
    'Kuyang Ketawa',
    'Tuyul Genit',
    'Hantu Ketawa',
    'Kuntilanak Ketawa',
    'Jelangkung Ketawa',
    'Wewe Gombel Ketawa',
    'Tuyul Joget',
    'Pocong Ketawa',
    'Sundel Bolong Ketawa',
    'Kuntilanak Joget',
    'Buto Ijo Joget',
    'Leak Joget',
    'Buto Putih Joget',
    'Kuyang Joget',
    'Tuyul Happy',
    'Hantu Joget',
    'Kuntilanak Joget',
    'Jelangkung Joget',
    'Wewe Gombel Joget',
    'Tuyul Selfie',
    'Pocong Joget',
    'Sundel Bolong Joget',
    'Kuntilanak Happy',
    'Buto Ijo Happy',
    'Leak Happy',
    'Buto Putih Happy',
    'Kuyang Happy',
    'Tuyul Lucu',
    'Hantu Happy',
    'Kuntilanak Happy',
    'Jelangkung Happy',
    'Wewe Gombel Happy',
    'Tuyul Ketawa',
    'Pocong Happy',
    'Sundel Bolong Happy',
    'Kuntilanak Ketawa',
    'Buto Ijo Ketawa',
    'Leak Ketawa',
];
